# ==============================================================================
version: "3.8"

# ==============================================================================
services:

  jekyll:
    image: "jekyll/jekyll:latest"
    command: jekyll serve --force_polling --livereload --incremental
    volumes:
      - ./docs:/srv/jekyll
    ports:
      - 35729:35729
      - 4000:4000