# ==============================================================================
version: "3.8"

# ==============================================================================
services:

  jekyll:
    image: "jekyll/jekyll:latest"
    command: jekyll serve --source ./docs --config "docs/_config.yml" --force_polling --livereload --incremental
    volumes:
      - ./:/srv/jekyll
    ports:
      - 35729:35729
      - 4000:4000